title: Muhammad Tayyab Sheikh
email: cstayyab@gmail.com
profile-image: "/assets/images/me.jpg"
description: >-
  linux advocate, opensource enthusiast, passionate computer programmer
baseurl: ""
url: ""
github_username: cstayyab
linkedin_username: cstayyab
twitter_username: CSTayyab
facebook_username: CSTayyab
instagram_username: cstayyab

markdown: kramdown
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - portfolio.md
  - contributions.md
  - contact.md

collections:
  projects:
    output: true
  contributions:
    output: false

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE 