title: Muhammad Tayyab Sheikh
email: cstayyab@gmail.com
profile-image: "/assets/images/me.jpg"
logo: /assets/images/me.jpg
description: >-
  linux advocate, opensource enthusiast, passionate computer programmer
baseurl: "https://cstayyab.github.io"
url: "https://cstayyabgithub.io"
github_username: cstayyab
linkedin_username: cstayyab
twitter_username: CSTayyab
facebook_username: CSTayyab
instagram_username: cstayyab

author:
  twitter: cstayyab
  picture: /assets/images/me.jpg
twitter:
  username: cstayyab
  card: summary
social:
  name: Muhammad Tayyab Sheikh (CS Tayyab)
  links:
    - https://twitter.com/CSTayyab
    - https://www.facebook.com/CSTayyab
    - https://www.linkedin.com/in/cstayyab
    - https://github.com/cstayyab

webmaster_verifications:
  google: TqGymtPmzd7kEfekzkEqaKTQHtuwyOBUyS6i5CjbTzU

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - index.md
  - portfolio.md
  - contributions.md
  - contact.md

collections:
  projects:
    output: true
  contributions:
    output: false

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE 
include:
  - _redirects